[project]
name = "template"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "torch",
    "transformers",
    "datasets",
    "tiktoken",
    "torcheval"
]
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
template = "template.__main__:main"

[dependency-groups]
dev = [
    "template",
]

[tool.uv.sources]
template = { workspace = true }

