[project]
name = "template"
version = "0.0.1"
requires-python = ">= 3.11"
dependencies = [
    "numpy",
    "torch",
    "transformers",
    "datasets",
    "tiktoken",
    "torcheval"
]

[project.scripts]

template = "template.__main__:main"
