experiment_name = "shakespeare_gpt"
dataset = "shakespeare_char"
always_save_checkpoint = false
log_interval = 1
eval_only = false
device_type = "cpu"
compile = false
learning_rate = 1e-3
min_lr = 1e-3
decay_lr = false
lr_decay_iters = 600000
weight_decay = 1e-1
beta1 = 0.9
beta2 = 0.95
grad_clip = 1.0
eval_interval = 100
eval_iters = 10
gradient_accumulation_steps = 1
warmup_iters = 2000
max_iters = 20000
backend = "nccl"
dtype = "float32"
epoch = 30
n_layer = 4
n_head = 4
n_vocab = 65
d = 128
sequence_length = 64
dropout = 0.00
bias = false
freeze = false
n_sample = 3
batch_size =12
n_embd = 128
